filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config.enabled: false

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

setup:
  kibana:
    host: '${KIBANA_HOST:http://kibana:5601}'
  dashboards:
    enabled: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:http://elasticsearch:9200}'
