version: '3'
services:
  # Service subkey order: build/image, entrypoint, command, * (alphabetically)
  # Beware: https://github.com/docker-library/docs/tree/master/openjdk#environment-variables-with-periods-in-their-names

  session: # Map to host ports 14xxx.
    # First follow README.md to build this Docker image.
    image: govsso-session:latest
    depends_on:
      - tara
    deploy:
      resources:
        limits:
          memory: 650M
    environment:
      - server.port=8080
      # Override built-in application.yml URL-s to use container hostnames ("oidc", "tara") from docker-compose.yml,
      #  except auth-url, which must use a hostname that browser running on host machine can access ("localhost").
      - govsso.hydra.admin-url=http://oidc:4445/
      - govsso.tara.issuer-url=https://tara.localhost:15443
      - BPL_DEBUG_ENABLED=true
      # TODO Tune memory calculator (see https://stackoverflow.com/a/67595951 for more information).
      - BPL_JVM_THREAD_COUNT=10
    ports:
      - '14000:8000'
      - '14080:8080'
    #restart: unless-stopped
