version: '3'
services:
  # Service subkey order: build/image, entrypoint, command, * (alphabetically)
  # Beware: https://github.com/docker-library/docs/tree/master/openjdk#environment-variables-with-periods-in-their-names
  # TODO Replace sleep with a reliable mechanism.

  clienta: # Map to host ports 11xxx.
    # TODO Use GOVSSO-Client instead.
    build: https://github.com/e-gov/TARA-Client.git
    entrypoint: sh -c 'sleep 10 && java -jar $$JAVA_OPTS /tara-client-jar-with-dependencies.jar'
    depends_on:
      - oidc
    deploy:
      resources:
        limits:
          memory: 650M
    environment:
      - JAVA_OPTS=-Dprovider.domain=oidc -Dprovider.port=4444 -Dprovider.discovery.endpoint=.well-known/openid-configuration -Dclient.port=11443
    ports:
      - '11443:11443'
    #restart: unless-stopped

  # TODO clientb
  # Map to host ports 12xxx.

  oidc: # Map to host ports 13xxx.
    image: oryd/hydra:v1.10.6-sqlite # hydra:v1.10.6 image doesn't have shell, -sqlite image does.
    entrypoint: sh -c 'hydra migrate sql --read-from-env --yes && hydra serve --config /etc/hydra/hydra.yml all --dangerous-force-http'
    depends_on:
      - oidc-db
    deploy:
      resources:
        limits:
          memory: 250M
    environment:
      - DSN=postgres://hydra:changeme@oidc-db:5432/oidc-db?sslmode=disable&max_conns=20&max_idle_conns=4
      # Configure endpoints advertised in /.well-known/openid-configuration to use container's hostname "oidc".
      - URLS_SELF_ISSUER=http://oidc:4444/
      # Override auth endpoint advertised in /.well-known/openid-configuration to use hostname that browser running on host machine can access ("localhost").
      - WEBFINGER_OIDC_DISCOVERY_AUTH_URL=http://localhost:13444/oauth2/auth
      # Configure Hydra to redirect to session-service endpoints by hostname that browser running on host machine can access ("localhost").
      - URLS_LOGIN=http://localhost:14080/login
      - URLS_CONSENT=http://localhost:14080/consent
      - URLS_LOGOUT=http://localhost:14080/logout
      - URLS_ERROR=http://localhost:14080/error
    ports:
      - '13444:4444'
      - '13445:4445'
    #restart: unless-stopped
    volumes:
      - ./local/oidc:/etc/hydra

  # TODO Import initial client data through admin service.
  oidc-setup:
    image: oryd/hydra:v1.10.6-sqlite # hydra:v1.10.6 image doesn't have shell, -sqlite image does.
    entrypoint: sh -c 'sleep 10 && hydra clients create --id openIdDemo --secret secret --callbacks https://localhost:11443/oauth/response'
    depends_on:
      - oidc
    deploy:
      resources:
        limits:
          memory: 250M
    environment:
      - HYDRA_ADMIN_URL=http://oidc:4445/

  tara: # Map to host ports 15xxx.
    # TODO Use specific version.
    # TODO Optimize Dockerfile (use multi-stage to exclude build environment).
    build:
      context: https://github.com/e-gov/TARA-Mock.git
      args:
        genkeys: 'true'
    deploy:
      resources:
        limits:
          memory: 250M
    ports:
      - '15443:8443'
    #restart: unless-stopped
    volumes:
      - ./local/tara/config.json:/service/config.json

  admin: # Map to host ports 16xxx.
    # First follow TARA2-Admin README.md to build this Docker image.
    image: tara-admin:latest
    depends_on:
      - admin-db
      - oidc
      - smtp
    deploy:
      resources:
        limits:
          memory: 650M
    environment:
      - tara-oidc.url=http://oidc:4445/
      - spring.datasource.url=jdbc:postgresql://admin-db:5432/admin-db
      - spring.mail.host=smtp
      - spring.mail.port=1025
      - spring.mail.username=
      - spring.mail.password=
      - spring.mail.properties.mail.smtp.auth=false
      - spring.mail.properties.mail.smtp.starttls.enable=false
      - tara.admin.sso-mode=true
      # TODO Tune memory calculator (see https://stackoverflow.com/a/67595951 for more information).
      - BPL_JVM_THREAD_COUNT=10
    ports:
      - '16080:8080'
    #restart: unless-stopped

  smtp: # Map to host ports 17xxx.
    image: mailhog/mailhog:v1.0.1
    ports:
      - '17080:8025'

  oidc-db:
    image: postgres:13
    deploy:
      resources:
        limits:
          memory: 250M
    environment:
      - POSTGRES_DB=oidc-db
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=changeme
    #restart: unless-stopped
    volumes:
      - oidc-db-data:/var/lib/postgresql/data

  admin-db:
    image: postgres:13
    deploy:
      resources:
        limits:
          memory: 250M
    environment:
      - POSTGRES_DB=admin-db
      - POSTGRES_USER=taraadmin
      - POSTGRES_PASSWORD=changeme
    #restart: unless-stopped
    volumes:
      - admin-db-data:/var/lib/postgresql/data

volumes:
  oidc-db-data:
  admin-db-data:
