version: '3'
services:
  # Service subkey order: build/image, entrypoint, command, * (alphabetically)
  # Beware: https://github.com/docker-library/docs/tree/master/openjdk#environment-variables-with-periods-in-their-names
  # TODO Replace sleep with a reliable mechanism.

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '9080:8080'

  clienta: # Map to host ports 11xxx.
    image: govsso-client:latest
    entrypoint: bash -c 'sleep 15 && /cnb/process/web'
    depends_on:
      - oidc
    deploy:
      resources:
        limits:
          memory: 650M
    environment:
      - server.port=11443
      - spring.application.name=Client A
      - spring.security.oauth2.client.registration.govsso.client-id=client-a
      - spring.security.oauth2.client.registration.govsso.client-secret=secreta
      - spring.security.oauth2.client.provider.govsso.issuer-uri=http://oidc.localhost:13444/
      - govsso.public-url=https://localhost:11443
      - govsso.logo=client-a.png
    ports:
      - '11443:11443'
    #restart: unless-stopped

  clientb: # Map to host ports 12xxx.
    image: govsso-client:latest
    entrypoint: bash -c 'sleep 15 && /cnb/process/web'
    depends_on:
      - oidc
    deploy:
      resources:
        limits:
          memory: 650M
    environment:
      - server.port=12443
      - spring.application.name=Client B
      - spring.security.oauth2.client.registration.govsso.client-id=client-b
      - spring.security.oauth2.client.registration.govsso.client-secret=secretb
      - spring.security.oauth2.client.provider.govsso.issuer-uri=http://oidc.localhost:13444/
      - govsso.public-url=https://localhost:12443
      - govsso.logo=client-b.png
    ports:
      - '12443:12443'
    #restart: unless-stopped

  oidc: # Map to host ports 13xxx.
    image: oryd/hydra:v1.10.7-sqlite # hydra:v1.10.7 image doesn't have shell, -sqlite image does.
    entrypoint: sh -c 'sleep 7 && hydra migrate sql --read-from-env --yes && hydra serve --config /etc/hydra/hydra.yml all --dangerous-force-http'
    depends_on:
      - oidc-db
    deploy:
      resources:
        limits:
          memory: 250M
    environment:
      - SERVE_PUBLIC_PORT=13444
      - DSN=postgres://hydra:changeme@oidc-db:5432/oidc-db?sslmode=disable&max_conns=20&max_idle_conns=4
      - URLS_SELF_ISSUER=http://oidc.localhost:13444/
      # Configure Ory Hydra to redirect to session-service endpoints by hostname that browser running on host machine can access ("localhost").
      - URLS_LOGIN=http://localhost:14080/auth/init
      - URLS_CONSENT=http://localhost:14080/auth/consent
      - URLS_LOGOUT=http://localhost:14080/logout
      - URLS_ERROR=http://localhost:14080/error
    networks:
      default:
        aliases:
          - oidc.localhost
    ports:
      - '13444:13444'
      - '13445:4445'
    #restart: unless-stopped
    volumes:
      - ./local/oidc:/etc/hydra

  setup:
    build: local/setup
    depends_on:
      - admin
    deploy:
      resources:
        limits:
          memory: 250M
    environment:
      - ADMIN_SERVICE_URL=http://admin:8080
      - ADMIN_USER=admin
      - ADMIN_PASS=admin

  tara: # Map to host ports 15xxx.
    # TODO Use specific version.
    # TODO Optimize Dockerfile (use multi-stage to exclude build environment).
    build:
      context: https://github.com/e-gov/TARA-Mock.git
      args:
        genkeys: 'true'
    deploy:
      resources:
        limits:
          memory: 250M
    networks:
      default:
        aliases:
          - tara.localhost
    ports:
      - '15443:15443'
    #restart: unless-stopped
    volumes:
      - ./local/tara/config.json:/service/config.json

  admin: # Map to host ports 16xxx.
    # First follow TARA2-Admin README.md to build this Docker image.
    image: tara-admin:latest
    depends_on:
      - admin-db
      - oidc
      - smtp
    deploy:
      resources:
        limits:
          memory: 650M
    environment:
      - tara-oidc.url=http://oidc:4445/
      - spring.datasource.url=jdbc:postgresql://admin-db:5432/admin-db
      - spring.mail.host=smtp
      - spring.mail.port=1025
      - spring.mail.username=
      - spring.mail.password=
      - spring.mail.properties.mail.smtp.auth=false
      - spring.mail.properties.mail.smtp.starttls.enable=false
      - tara.admin.sso-mode=true
      - BPL_DEBUG_ENABLED=true
      # TODO Tune memory calculator (see https://stackoverflow.com/a/67595951 for more information).
      - BPL_JVM_THREAD_COUNT=10
    ports:
      - '16000:8000'
      - '16080:8080'
    #restart: unless-stopped

  smtp: # Map to host ports 17xxx.
    image: mailhog/mailhog:v1.0.1
    ports:
      - '17025:1025'
      - '17080:8025'

  oidc-db:
    image: postgres:13
    deploy:
      resources:
        limits:
          memory: 250M
    healthcheck:
      test: pg_isready -U hydra -d oidc-db
      interval: 6s
      retries: 10
    environment:
      - POSTGRES_DB=oidc-db
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=changeme
    ports:
      - '18432:5432'
    #restart: unless-stopped
    volumes:
      - oidc-db-data:/var/lib/postgresql/data

  admin-db:
    image: postgres:13
    deploy:
      resources:
        limits:
          memory: 250M
    environment:
      - POSTGRES_DB=admin-db
      - POSTGRES_USER=taraadmin
      - POSTGRES_PASSWORD=changeme
    ports:
      - '19432:5432'
    #restart: unless-stopped
    volumes:
      - admin-db-data:/var/lib/postgresql/data

volumes:
  oidc-db-data:
  admin-db-data:
