openapi: '3.0.3'
info:
  title: GovSSO Session Service
  version: 0.1.0
servers:
  - url: https://session.localhost:15443
paths:
  /login/init:
    get:
      summary: Start authentication.
      operationId: authInit
      parameters:
        - in: query
          name: login_challenge
          description: ID of Ory Hydra's login request.
          required: true
          schema:
            type: string
            pattern: '^[a-f0-9]{32}$'
            minLength: 32
            maxLength: 32
            example: '824113da6da44889943b98715a06d699'
      responses:
        '302':
          description: Redirect to TARA for authentication.
          headers:
            Set-Cookie:
              description: Session cookie.
              schema:
                type: string
              example: SESSION=Nzc5ODFlZTktODhhNS00ZTEwLTk0NWQtN2EzNTU5N2E2MmY5; Path=/; HttpOnly; SameSite=Lax
            Location:
              description: TARA authentication request.
              schema:
                type: string
                format: uri
              example: scope=openid&response_type=code&redirect_uri=http%3A%2F%2Fsession.localhost:15443%2Fauth%2Ftaracallback&state=1CdQPV8h6Oej8czeP2GJiqLOkUR70yIPlTNd16DBwGM&nonce=O15XCSiGW2FMeU0u9nN0kNEnwY9mfO7xOm-9wV5KQpI&client_id=govsso
        '400':
          description: User error (invalid request etc).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/html:
              schema:
                type: string
                example: HTML error view.
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/html:
              schema:
                type: string
                example: HTML error view.
  /login/taracallback:
    get:
      summary: TARA authentication completed, request ID token from TARA.
      operationId: authTaraCallback
      parameters:
        - in: cookie
          name: SESSION
          description: Session cookie.
          required: true
          schema:
            type: string
            pattern: '^[A-Za-z0-9]{48}$'
            minLength: 48
            maxLength: 48
            example: Nzc5ODFlZTktODhhNS00ZTEwLTk0NWQtN2EzNTU5N2E2MmY5
        - in: query
          name: code
          description: Authorization code to use for requesting ID token from TARA.
          required: true
          schema:
            type: string
            pattern: '^[A-Za-z0-9\-_.]{6,87}$'
            minLength: 6
            maxLength: 87
            example: gSVzQ6iWTLWDtD1f7_QZdHNweXzrraQYdys_MWoRK-A.nQ2epEBSzxo_n-P6hQt_I_HvusERdqkGaC31TrjSIlU
        - in: query
          name: state
          description: Security code against false request attacks.
          required: true
          schema:
            type: string
            pattern: '^[A-Za-z0-9\-_]{43}$'
            minLength: 43
            maxLength: 43
            example: 1CdQPV8h6Oej8czeP2GJiqLOkUR70yIPlTNd16DBwGM
      responses:
        '302':
          description: ID token from TARA obtained successfully, redirect to Ory Hydra for accepting login request.
          headers:
            Location:
              description: Ory Hydra accept login request.
              schema:
                type: string
                format: uri
              example: https://hydra.localhost:14443/oauth2/auth?client_id=client-a&login_verifier=824113da6da44889943b98715a06d699&redirect_uri=https%3A%2F%2Flocalhost:11443%2Foauth%2Fresponse&response_type=code&scope=openid&state=I00ORQdhpLdhZVa5mliUexwkWFevHV0Z8Xuh7gaps0E%3D
        '400':
          description: User error (invalid request etc).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/html:
              schema:
                type: string
                example: HTML error view.
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/html:
              schema:
                type: string
                example: HTML error view.
  /auth/consent:
    get:
      summary: Display consent view.
      operationId: authConsent
      parameters:
        - in: cookie
          name: SESSION
          description: Session cookie.
          required: true
          schema:
            type: string
            pattern: '^[A-Za-z0-9]{48}$'
            minLength: 48
            maxLength: 48
            example: Nzc5ODFlZTktODhhNS00ZTEwLTk0NWQtN2EzNTU5N2E2MmY5
        - in: query
          name: consent_challenge
          description: ID of Ory Hydra's consent request.
          required: true
          schema:
            type: string
            pattern: '^[a-f0-9]{32}$'
            minLength: 32
            maxLength: 32
            example: '01a9d709fb014160b4f1016bf7868574'
      responses:
        '302':
          description: Consent display skipped, redirect to Ory Hydra for accepting consent request.
          headers:
            Location:
              description: Ory Hydra accept consent request.
              schema:
                type: string
                format: uri
              example: https://hydra.localhost:14443/oauth2/auth?client_id=client-a&consent_verifier=01a9d709fb014160b4f1016bf7868574&redirect_uri=https%3A%2F%2Flocalhost:11443%2Foauth%2Fresponse&response_type=code&scope=openid&state=I00ORQdhpLdhZVa5mliUexwkWFevHV0Z8Xuh7gaps0E%3D
        '400':
          description: User error (invalid request etc).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/html:
              schema:
                type: string
                example: HTML error view.
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/html:
              schema:
                type: string
                example: HTML error view.
components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - timestamp
        - status
        - error
      properties:
        timestamp:
          type: string
          description: Time that the error occurred.
          example: '2020-12-22T09:09:23.463+00:00'
        status:
          type: integer
          format: int32
          description: HTTP status code.
          example: 400
        error:
          type: string
          description: Error code.
          example: USER_INPUT_OR_EXPIRED
        message:
          type: string
          description: Human readable error description.
          example: Invalid request or request has expired. Please return to service provider and try again.
        path:
          type: string
          description: URL path when the error occurred.
          example: /sample/path
