management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        # TODO Disable most endpoints in non-dev environments.
        include: '*'

spring:
  main:
    banner-mode: off

server:
  # Use same port as docker-compose-all.yml.
  port: 14080

govsso:
  # By default use URL-s accessible from host machine ("localhost") to support "Running GOVSSO Session Service Locally
  #  and Dependencies in Docker Compose" workflow in README.md.
  base-url: http://localhost:14080/
  hydra:
    base-url: http://localhost:13444/
    admin-url: http://localhost:13445/
  tara:
    discovery-url: https://localhost:15443/oidc/.well-known/openid-configuration
    jwks-url: https://localhost:15443/oidc/jwks
    auth-url: https://localhost:15443/oidc/authorize
    token-url: https://localhost:15443/oidc/token
    client-id: govsso
    client-secret: changeme
